
-------- supprimer la base-----------


DROP TABLE etudiant CASCADE CONSTRAINTS

DROP TABLE pointArret CASCADE CONSTRAINTS

DROP TABLE  trajet CASCADE CONSTRAINTS

DROP TABLE avis CASCADE CONSTRAINTS

DROP TABLE  voiture CASCADE CONSTRAINTS

DROP TABLE inscription CASCADE CONSTRAINTS

DROP TABLE inclusion CASCADE CONSTRAINTS